dist: xenial

sudo: required
services:
  - docker

language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2/repository

before_script:
  - java -version

script:
  - sh .travis/run.sh

