sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_script:
  - java -version

script:
  - |
    mvn test > test.log 2>&1
    tail -n1000 test.log

